### ISSUE TITLE
Is there a build version where we can just download

### ISSUE THREAD

**Issue by bitdom8** [vddCore/Zephyrus-Control-Center#3]
I don't want to build myself, is there a better way? Also started using Nobara with Windows, is linux support on the way?

**Comment by vddCore** [comment]
Hey there. I'm not planning any more updates to this in the foreseeable future - I've left Windows ecosystem for good, so... Yeah. But! I've recently started a side-project to act as Linux counterpart to this, no ETA though as I got my hands full with other things at the moment and in the coming months.

As for the build - I've just re-triggered a pipeline run. Head [over here](https://github.com/vddCore/Zephyrus-Control-Center/actions/runs/8408414872) and scroll down - an artifact package will be waiting there.

Please note that lots of things might've changed since I last worked with ASUS hardware on Windows, so no guarantees it's going to work!

Cheers!
